### ISSUE TITLE
There is problem with transforming html style attributes

### ISSUE THREAD

**Issue by pkawula** [swc-project/swc-node#627]
Here is an error I've received:

```
  ● Test suite failed to run

    error: Expected '>', got 'style'
     
      |
    2 |     return <span style={{ display: "block", width: "10px", height: "10px", backgroundColor: "#ffffff" }} />
      |                  ^^^^^



    Caused by:
        0: failed to process js file
        1: Syntax Error

      at Compiler.transformSync (node_modules/@swc/core/index.js:135:25)
      at transformSync (node_modules/@swc/core/index.js:215:21)
      at transformJest (node_modules/@swc-node/core/index.ts:72:26)
      at Object.process (node_modules/@swc-node/jest/index.ts:30:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:612:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.38 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

Here is my config for jest.config.js:
```
module.exports = {
	globalSetup: "<rootDir>/setupTestEnv.js",
	setupFilesAfterEnv: ["./setupTests.js"],
	testPathIgnorePatterns: ["<rootDir>/node_modules", "<rootDir>/cypress"],
	moduleNameMapper: {
		"^~/components(.*)$": "<rootDir>/src/components$1",
		"^~/containers(.*)$": "<rootDir>/src/containers$1",
		"^~/api(.*)$": "<rootDir>/src/api$1",
		"^~(.*)$": "<rootDir>/src$1",
		"^@/public(.*)$": "<rootDir>/public$1",
		"^@/local(.*)$": "<rootDir>/local$1",
		".+\\.(css|sass|less|scss)$": "<rootDir>/mocks/styles.js"
	},
	transform: {
		"^.+\\.(js|jsx|ts|tsx)$": "@swc-node/jest",
		".+\\.(jpg|png|jpeg|gif)$": "jest-transform-stub",
		".+.svg": "<rootDir>/mocks/svgs.js"
	}
};
```

Is there a missing package in configuration or this feature is not iplemented yet?

**EDIT**
I also noticed that if I remove the style attribute it works fine, but then appears another error:
```
src/components/Test/index.test.js
  ● Test suite failed to run

    error: Expression expected
      
       |
    11 |         render(<TestComponent />);
       |                               ^

    error: Expression expected
      
       |
    11 |         render(<TestComponent />);
       |                                ^

    error: Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier
      
       |
    11 |         render(<TestComponent />);
       |                                 ^



    Caused by:
        0: failed to process js file
        1: Syntax Error

      at Compiler.transformSync (node_modules/@swc/core/index.js:135:25)
      at transformSync (node_modules/@swc/core/index.js:215:21)
      at transformJest (node_modules/@swc-node/core/index.ts:72:26)
      at Object.process (node_modules/@swc-node/jest/index.ts:30:27)
      ```
      
      and test be like:
      ```
      describe("Test component", () => {
	it("Displays fetched data", async () => {
		render(<TestComponent />);

		const author = await screen.findByTestId("result");

		expect(author).toHaveTextContent("Author: John Maverick");
	});
});
```

**Comment by Brooooooklyn** [comment]
I guess you have a `jsx` file with `.js` file extension. `@swc-node/jest` detect the `jsx` option by the file extension. But you could always enable `jsx` but lost some speed:

````js
transform: {
  "^.+\\.(js|jsx|ts|tsx)$": ["@swc-node/jest", { jsx: true }],
}
```

**Comment by pkawula** [comment]
Thats an idea, then something changes and I have another error:
```
 FAIL  src/components/__tests__/Message.test.tsx
  ● Test suite failed to run

    TypeError: Cannot set property render of [object Object] which has only a getter

      25 | export * from "@testing-library/react";
      26 |
    > 27 | export { customRender as render };
         |                                ^
      28 |

      at Object.<anonymous> (src/helpers/tests.tsx:27:32)
      at Object.<anonymous> (src/components/__tests__/Message.test.tsx:4:41)
      ```
      
      I think it can be related to similar for babel [https://stackoverflow.com/a/53307822/9094066](https://stackoverflow.com/a/53307822/9094066)
      Problem might be the  same, because I reexport  a providers for an App:
      ```
      const Providers = ({ children }) => (
	<Provider store={store}>
		<EventProvider observers={[Gtag, PostAffiliatePro]}>
			<ProductsListContextProvider>{children}</ProductsListContextProvider>
		</EventProvider>
	</Provider>
);

const customRender = (
	ui: ReactElement<any, string | JSXElementConstructor<any>>,
	options: RenderOptions = {}
) => render(ui, { wrapper: Providers, ...options });

export * from "@testing-library/react";

export { customRender as render };
```

**Comment by pkawula** [comment]
I am closing this, because it is working now
