### ISSUE TITLE
Register fails when entrypoint is a `commonjs` vscode extension

### ISSUE THREAD

**Issue by psychobolt** [swc-project/swc-node#795]
**Issue**

Hi, I am trying to execute my custom runtime with a vscode extension. However, I am getting this error in outputs:

```
[Info  - 10:13:43 AM] ESLint server is starting.
URL:file:///Users/mitran/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js

node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: Failed to convert JavaScript value `Undefined` into rust type `String`
    at Compiler.<anonymous> (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-core-virtual-d7e358b2c0/node_modules/@swc/core/index.js:218:33)
    at Generator.next (<anonymous>)
    at /Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-core-virtual-d7e358b2c0/node_modules/@swc/core/index.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-core-virtual-d7e358b2c0/node_modules/@swc/core/index.js:27:12)
    at Compiler.transform (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-core-virtual-d7e358b2c0/node_modules/@swc/core/index.js:203:16)
    at transform (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-core-virtual-d7e358b2c0/node_modules/@swc/core/index.js:352:21)
    at transform (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/__virtual__/@swc-node-core-virtual-849eb160d1/3/.yarn/berry/cache/@swc-node-core-npm-1.13.1-7bd6e51ef2-10c0.zip/node_modules/@swc-node/core/lib/index.js:71:33)
    at compile (/Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-node-register-virtual-ef6475fd81/node_modules/@swc-node/register/lib/register.js:81:37)
    at load (file:///Users/mitran/Projects/vite-storybook-boilerplate/.yarn/unplugged/@swc-node-register-virtual-ef6475fd81/node_modules/@swc-node/register/esm/esm.mjs:183:28) {
  code: 'StringExpected'
}

Node.js v20.15.0
```

What would be executed for example would be `ESLINT_USE_FLAT_CONFIG=true node bin/swc-node.js "../../.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js" -c eslint.config.ts`.

**Analysis**

It seems that any `commonjs` file would cause the same error. For example I've created a simple test:

```
// foo.cjs
module.exports = {
  foo: 'bar'
};
```

```sh
node --import @swc-node/register ./foo.cjs
```

Would recieve the saem error:
```sh
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: Failed to convert JavaScript value `Undefined` into rust type `String`
```

**Comment by fargito** [comment]
I have the same issue, however I think it is not specific to VSCode extension. I encounter it when I import a `commonjs` file with node. I opened #796 but I think my fix was incorrect, so I closed it.

**Comment by fargito** [comment]
I'm even wondering if `commonjs` files should be skipped altogether?

in `packages/register/esm.mts`
```diff
export const load: LoadHook = async (url, context, nextLoad) => {
  debug('load', url, JSON.stringify(context))

  if (url.startsWith('data:')) {
    debug('skip load: data url', url)

    return nextLoad(url, context)
  }

  if (['builtin', 'json', 'wasm'].includes(context.format)) {
    debug('loaded: internal format', url)
    return nextLoad(url, context)
  }

+  if (context.format === "commonjs") {
+    debug('skip load: commonjs file', url);
+    return nextLoad(url, context);
+  }

  const { source, format: resolvedFormat } = await nextLoad(url, context)

  debug('loaded', url, resolvedFormat)

  const code = !source || typeof source === 'string' ? source : Buffer.from(source).toString()
  const compiled = await compile(code, url, tsconfigForSWCNode, true)

  debug('compiled', url, resolvedFormat)

  return addShortCircuitSignal({
    // for lazy: ts-node think format would undefined, actually it should not, keep it as original temporarily
    format: resolvedFormat,
    source: compiled,
  })
}

```

WDYT @Brooooooklyn?

**Comment by yeliex** [comment]
> I'm even wondering if commonjs files should be skipped altogether?

definitely no. import commonjs in esm is a very common case

> I would assume we need a [similar fallback](https://github.com/swc-project/swc-node/blob/9644be5577f77aa53f974636fac4bc38f77148ce/packages/register/esm.mts#L196), which fixed the Yarn loader https://github.com/swc-project/swc-node/issues/772#issuecomment-2094771696

A workaround should be. but ignoring by path prefix is too rude. I would look at this, maybe we could have a better way.

**Comment by yeliex** [comment]
could you please provide a minimal reproduction

**Comment by psychobolt** [comment]
Got a different error on this [sandbox](https://codesandbox.io/p/devbox/swc-register-commonjs-l9nfsp), but fails on `commonjs` script. Possibly related?
