### ISSUE TITLE
swc-node/register resolve to wrong path

### ISSUE THREAD

**Issue by hax** [swc-project/swc-node#846]
Assume I have `test.js`, I can run `node --import ./test.js` well.

But c fail:
```
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^
Error: All of the aliased extensions are not found for /hax/test1.js: ./test1.js cannot be resolved in file:///hax/x/
    at resolve (file:///hax/x/node_modules/@swc-node/register/esm/esm.mjs:157:15)
    at async nextResolve (node:internal/modules/esm/hooks:866:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:304:24)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18)

Node.js v20.16.0
```

I notice the dir seems become parent dir, and found that `node --import @swc-node/register/esm-register/esm-register --import ./x/test.js` works.

Note, version 1.10.0 is ok (though not support `--import ./test.ts`). It seems become broken from 1.10.1 .

**Comment by benzittlau** [comment]
I am getting this same error when attempting to import `bignumber.js` using `swc-node/register` which I wasn't seeing previously utilizing `ts-node`. I've created a repo that reproduces the issue here:

https://github.com/benzittlau/swc-import-error-reproduction-repo

It seems like it may be related to it needing to be in a yarn workspace as I wasn't able to reproduce the issue without the yarn workspace hoisting involved:

```
Error: All of the aliased extensions are not found for /.../swc-import-bug/package/node_modules/bignumber.js: bignumber.js cannot be resolved in file:///.../swc-import-bug/package/src/index.ts
    at resolve (file:///.../swc-import-bug/node_modules/@swc-node/register/esm/esm.mjs:157:15)
    at async nextResolve (node:internal/modules/esm/hooks:865:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:303:24)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18)
 ```

**Comment by wasd171** [comment]
I am getting a similar issue, the problem is here

https://github.com/swc-project/swc-node/blob/5ab459dfc138ed27dd78c976e8b079144d03b706/packages/register/esm.mts#L227

Specifically, this is because for `--import`s `context.parentURL` is a directory `../../`, so when you attempt to go 1 level up it is not possible (as expected) to find the module.

Something like this needs to be done:
```ts
const getDirectory = (fileOrDirectory: string) => {
	if (fileOrDirectory.endsWith('/')) {
		return fileOrDirectory
	} else {
		return join(fileOrDirectory, '..')
	}
}

... await resolver.async(getDirectory(fileURLToPath(context.parentURL)), ...)
```

@Brooooooklyn would you be willing to accept a PR for this?
